INSERT INTO articulos (id, id_ubicacion, id_inventario, nombre_articulo, descripcion, categoria, estado_articulo, cantidad, fecha_adquisicion, proveedor, direccion_imagen, codigo_barras, precio) VALUES
    (
         1,
         1,
         1,
         'Limpiador multiusos',
         'Elimina la suciedad y desinfecta.',
         'Limpieza',
         'Disponible',
         100,
         '2023-05-10',
         'Proveedor X',
         'src/main/resources/com/example/proyectofinaldb/assets/img/articulos/limpiador-multiusos.PNG',
         9911911280000,
         30
    ),
    (
         2,
         3,
         2,
         'Medicamento A',
         'Alivia dolores leves.',
         'Medicina',
         'Agotado',
         0,
         '2023-07-25',
         'Farmacia Y',
         'src/main/resources/com/example/proyectofinaldb/assets/img/articulos/paracetamol.PNG',
         100192822333,
         50
    ),
    (
         3,
         4,
         3,
         'Martillo',
         'Herramienta para golpear.',
         'Herramientas',
         'Disponible',
         20,
         '2023-09-01',
         'Ferreteria Z',
         'src/main/resources/com/example/proyectofinaldb/assets/img/articulos/martillo.PNG',
         1111911287436,
         60
    ),
    (
         4,
         2,
         4,
         'Refrigerador',
         'Electrodoméstico para conservar alimentos.',
         'Electrodomesticos',
         'Disponible',
         5,
         '2023-06-15',
         'Tienda Electro',
         'src/main/resources/com/example/proyectofinaldb/assets/img/articulos/refrijerador.PNG',
         357863324488,
         5000
    ),
    (
         5,
         5,
         5,
         'Camiseta',
         'Prenda de vestir.',
         'Ropa',
         'Disponible',
         30,
         '2023-10-02',
         'Tienda Moda',
         'src/main/resources/com/example/proyectofinaldb/assets/img/articulos/camiseta.PNG',
         2222,
         150
    ),
    (
         6,
         6,
         6,
         'Laptop Machinike',
         'Computadora Gaming',
         'Computacion',
         'Disponible',
         30,
         '2023-11-02',
         'Machinike',
         'src/main/resources/com/example/proyectofinaldb/assets/img/articulos/laptop.PNG',
         1111,
         20000
    );

SOURCE insert_ingresos.sql;